version: '3.4'

networks:
  laravel:
    driver: bridge
    ipam:
      config: 
        - subnet: 172.16.238.0/24

# services:
#   alpha:
#     image: alpha
#     build:
#       context: .
#       dockerfile: ./Dockerfile

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80" # binds local 8081 port with nignx's 80 port
    volumes:
      - C:/projects/laravel/Shonga:/var/www/html # apontar o caminho da pasta do projecto laravel
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw # apontar oo fichero de configuracao do nginx
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # apontar oo fichero de configuracao do nginx
      - ./nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    links:
      - php
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    volumes:
      - C:/DockerDev/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ermanadmin
    networks:
      - laravel
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports: 
      - "8082:8080"
    networks:
      - laravel
  php: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./php:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  composer:
    container_name: composer
    image: composer:latest
    command: ["composer", "install"]
    depends_on: 
      - php
    volumes:
      - ./code:/app
    restart: always
    networks:
      - laravel
  
